spring:
  datasource:
    url:  jdbc:mysql://212.64.34.214:3306/sina-hotsearch-db?useUnicode=true&characterEncoding=utf8mb4&useSSL=true
    username: root
    password: cfxz1997
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081